# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432